### ISSUE TITLE
Investigate growing resources usage until crash

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-elastic-indexer#144]
Running `pppy/osu-elastic-indexer:2023.823.0` in production, we are observing CPU and RAM usage growing on every instance, until it hits a `StackExchange.Redis.RedisTimeoutException` and crashes. This happens about every 30 minutes.

![image](https://github.com/ppy/osu-elastic-indexer/assets/4985725/f91afb6a-1e75-4db0-8e15-bf095e83a20b)

**Comment by smoogipoo** [comment]
@ThePooN Please check if this looks better for now and close if so :)

**Comment by peppy** [comment]
Confirmed resolved:

![Safari 2023-10-09 at 05 39 35](https://github.com/ppy/osu-elastic-indexer/assets/191335/6a0c67ea-6a61-4091-ad33-19a5b89a9f15)

<https://app.datadoghq.com/metric/explorer?graph_layout=multi&start=1696815568617&end=1696829968617&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyJlSCBiiOgB06qpuWI14GhjwwBqMbghOPt1wyDgVALRwmBoSmROiAsQ6PCA8ALpUru54M9ag26q7GDGl8WubILNYaDmg8hi3CAg5STgwTpkzGhCZiWgNJxyRTlHAAqD-QH0JjKERuDxoNb8CD2TBYIEKV4AkRKDY8PhXeQAhAAYSkwhgKBEuzQPCAA>

**Comment by ThePooN** [comment]
Seems good, has remained stable throughout the day.
