### ISSUE TITLE
Elasticsearch 7 compatibility

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-elastic-indexer#98]
The form of some of the queries currently being used won't work with ES7+ (especially the `index_meta` ones). 
This metadata should probably be moved into the `high_score` indices themselves; the metadata queries can be replaced by listing and filtering for matching indices.

**Comment by peppy** [comment]
Keep in mind we're also switching to a new storage format which is probably going to require a lot of changes here, so I wouldn't make any changes before that happens (will give more details in the next week or two).
